### PR TITLE
fix id and classes and css

### PR DESCRIPTION
**Pull request by signmeuptwice**
hopefully that helps

### CODE REVIEW

**Comment by jofftiquez** [comment]
WTH did you do to the README?

**Comment by signmeuptwice** [comment]
> WTH did you do to the README?

I changed it on my fork to reflect the npm publication... mistake ?

**Comment by igemnace** [comment]
> > WTH did you do to the README?
> 
> I changed it on my fork to reflect the npm publication... mistake ?

This is fine, I just don't believe we can make use of this PR in its current form.

Are there any changes from your fork that you believe would be useful for us? If so, you can isolate the work into a branch, free from any fork-specific changes (e.g. naming changes), and submit that as a PR.

**Comment by signmeuptwice** [comment]
Sorry kind of new to this... first fork for me... I believe the useful changes are up to 
769960e for you. I guess I could checkout the branch to 769960e ?

**Comment by igemnace** [comment]
Yep, that could work. We can review the changes in that case.

**Comment by signmeuptwice** [comment]
I have since uncovered quite a few other issues with the editor; in particular with loosing cursor selection. So I will be fixing those first before pr. I guess we can close this pr

**Comment by jofftiquez** [comment]
@signmeuptwice thanks. Please just don't do unnecessary customization to the README or other parts of the app.

**Pull request closed without merging**
